apiVersion: apps/v1
kind: Deployment
metadata:
  name: contosos
spec:
  replicas: 3
  selector:
    matchLabels:
      app: contosos
  template:
    metadata:
      labels:
        app: contosos
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: contosos
        image: contosocontainerregistry2.azurecr.io/contosoapp:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: contosoapp
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"  
  labels:
    run: contosoapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: contoso
