apiVersion: apps/v1
kind: Deployment
metadata:
  name: APPNAME
spec:
  replicas: 3
  selector:
    matchLabels:
      app: APPNAME
  template:
    metadata:
      labels:
        app: APPNAME
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: APPNAME
        image: IMAGENAME
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: app
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"  
  labels:
    run: app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: APPNAME
